In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(a.sum())

45


In [5]:
a.max()

9

In [8]:
a = np.array([[2,3,4,8,7,8,7],[6,7,8,9,5,3,2]])

In [9]:
a[1,4]

5

In [14]:
a.itemsize

4

In [15]:
a.min()

2

In [16]:
a.size

14

<h3>NP array operations</h3>

In [17]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

<h3>Comparision</h3>

In [19]:
#azq
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [21]:
np.array_equal(a,b)

False

In [22]:
np.array_equal(a,c)

True

<h3>Logical Operations</h3>

In [23]:
a = np.array([1,1,0,0], dtype = bool)

In [24]:
b = np.array([1,0,1,0], dtype = bool)

In [26]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [27]:
np.logical_and(a,b)

array([ True, False, False, False])

<h3>Some Other Functions</h3> 

In [28]:
np.sin(a)

array([0.8413, 0.8413, 0.    , 0.    ], dtype=float16)

In [29]:
np.log(a)

C:\Users\Rahul\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([  0.,   0., -inf, -inf], dtype=float16)

In [30]:
np.exp(a)

array([2.719, 2.719, 1.   , 1.   ], dtype=float16)